apiVersion: v1
kind: Service
metadata:
  name: delivery-boy-service
spec:
  selector:
    app: delivery-boy-service
  ports:
    - name: rabbitmq     
      protocol: TCP
      port: 3006
      targetPort: 3006
    - name: grpc        
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
